### ISSUE TITLE
Autloading package fails

### ISSUE THREAD

**Issue by Walheimat** [kubernetes-el/kubernetes-el#241] opened 2021-12-17 19:45 UTC
When trying to load the package from say `kubernetes-overview`, the following error occurs:

```
Symbol’s value as variable is void: kubernetes--process-ledger
```

Don't have time to look into it, but when I load `kubernetes-process.el` (where I guess this is defined) using `load-file`, it works again.

Since this seems to be using `defclass` macro I should maybe note that I'm on Emacs 29.0.50.

**Comment by Walheimat** [comment] 2021-12-17 19:50
Okay, so requiring `eieio` in that module solves it.

**Comment by jinnovation** [comment] 2021-12-17 20:39
> I think it's just the version currently on MELPA that's not working.

Do you know specifically what version got pulled in for you? 

I just pulled the current latest version—`20211217.1337`, corresponding to commit [24c720ba913fde2c8cfd370ed8bc07400ce2e358](https://github.com/kubernetes-el/kubernetes-el/tree/24c720ba913fde2c8cfd370ed8bc07400ce2e358), and `kubernetes-overview` runs w/o complaining about the void symbol. I am running Emacs 27.2.

Otherwise: Could you try pulling the latest version of the package and seeing if the issue pops up for you still?

**Comment by jinnovation** [comment] 2021-12-17 20:40
> I'm on Emacs 29.0.50

You bring up a good point here, actually. We currently test on Emacs 25 to 27. It's worthwhile for us to document the compatibility range in the README as well as expand the version range.

We'll ticket that up separately and follow up on that.

**Comment by jinnovation** [comment] 2021-12-17 21:00
By the way:
> I'm on Emacs 29.0.50

I assume you mean 28.0.50? Just to be clear.

**Comment by noorul** [comment] 2021-12-18 01:04
I tested this in 28.x before.

**Comment by Walheimat** [comment] 2021-12-18 20:01
The version I just tested with is `20211217.2055`, same error.

And yes, currently `master` branch is `29.0.50`.

It's strange though, when I load the package (with `use-package`) from a git clone, it works. For me this is good enough.

**Comment by jinnovation** [comment] 2021-12-18 21:27
> It's strange though, when I load the package (with `use-package`) from a git clone, it works. For me this is good enough.

Interesting, I'll try loading from MELPA package and see what happens. I'm loading directly from the Git repo as well, so maybe that's part of why I haven't run into this.

**Comment by jinnovation** [comment] 2021-12-19 15:31
I've installed Emacs 29.0.50 via Homebrew and run `M-x kubernetes-overview` and was unable to reproduce.

@Walheimat: Considering this package is not tested against Emacs `master` branch, and it sounds like you have a workaround, are you okay with us closing this issue?

I'll be submitting a PR separately to make it clearer what versions of Emacs we can "guarantee" this package working with.

**Comment by Walheimat** [comment] 2021-12-19 16:29
Yes, feel free to close.

**Closed** 2021-12-19 18:24 UTC
