### ISSUE TITLE
Deployments and Statefulsets are stuck in "Fetching..." state

### ISSUE THREAD

**Issue by andreasjansson** [kubernetes-el/kubernetes-el#131] opened 2021-04-15 18:57 UTC
I'm not sure how to debug this, but I'm including a screenshot here:

![image](https://user-images.githubusercontent.com/713993/114923342-8df86200-9de1-11eb-81eb-71342602a15f.png)

My cluster has deployments, but Kubernetes overview is not updating to display them. Happy to provide additional information.

Emacs version: 27.1
kubectl version: 1.19.7
Cluster version: v1.17.17-gke.2800

**Comment by noorul** [comment] 2021-04-16 00:00
Are you able to get these information using kubectl command from the same machine?

**Comment by andreasjansson** [comment] 2021-04-16 23:06
@noorul Thank you for the reply. Yes, `kubectl get deployments` and `kubectl get statefulsets` both work as expected on teh command line.

**Comment by noorul** [comment] 2021-04-16 23:47
@andreasjansson Can you double-check whether you are in the correct context and using the correct namespace?

**Comment by andreasjansson** [comment] 2021-04-17 15:03
@noorul Yep, it's using the correct context and namespace. I don't have any configmaps, and that section correctly reports `None`. Pods, secrets, services, and nodes are all populated with the expected resources.

**Comment by andreasjansson** [comment] 2021-04-17 16:15
I found the issue now, last time I worked on Kubernetes (over a year ago) I disabled deployments and statefulsets in `kubernetes-overview-custom-views-alist`. I remember doing that because statefulsets and deployments were duplicated in the listing. That could be why they appear in the list as stuck in "Fetching..." state, even though they weren't present in `kubernetes-overview-custom-views-alist`?

Now that I re-enable statefulsets and deployments in `kubernetes-overview-custom-views-alist`, they appear duplicated again in the listing:

![image](https://user-images.githubusercontent.com/713993/115119483-662e0900-9f5d-11eb-8a00-d54ba47c0f02.png)

**Comment by noorul** [comment] 2021-04-18 00:06
What is the current value of `kubernetes-overview-custom-views-alis`t ?

**Comment by noorul** [comment] 2021-04-18 22:02
@andreasjansson If it is working, shall we close this ticket?

**Comment by andreasjansson** [comment] 2021-04-19 16:30
@noorul, yes we can close this. I'll open a new one about statefulsets and deployments being duplicated. Something weird is going on there.

**Comment by jinnovation** [comment] 2021-05-03 02:40
For the record, I'm getting this issue on my end as well.

Some observations:
* The `overview` view does not successfully retrieve StatefulSets and Deployments
* The `deployments` view successfully retrieves Deployments
* On switching back to `overview` from `deployments`, Deployments display just fine
* Likewise for `statefulsets`

**Comment by noorul** [comment] 2021-05-03 09:52
@jinnovation Do you have the same settings  as https://github.com/chrisbarrett/kubernetes-el/issues/131#issuecomment-821847747 ?

**Comment by jinnovation** [comment] 2021-05-03 18:38
@noorul: My specs are as follows:
* Emacs version: 27.1
* kubectl version: 1.19.7
* Cluster version:  1.18.16-gke.2100

**Comment by noorul** [comment] 2021-05-08 20:54
@jinnovation  Can you share the value of variable ```kubernetes-overview-custom-views-alist```

**Comment by jinnovation** [comment] 2021-05-08 23:25
`nil`.

**Comment by willwu5047** [comment] 2021-06-04 05:38
i have same issue with (kubernetes-overview-custom-views-alist nil)

> For the record, I'm getting this issue on my end as well.
> 
> Some observations:
> 
> * The `overview` view does not successfully retrieve StatefulSets and Deployments
> * The `deployments` view successfully retrieves Deployments
> * On switching back to `overview` from `deployments`, Deployments display just fine
> * Likewise for `statefulsets`

**Comment by willwu5047** [comment] 2021-06-04 07:35
after statefulstes-refresh-now  the statefulset is display at overview buffer, but it't contain same error pods that's not stateful

![image](https://user-images.githubusercontent.com/84893968/120763883-3dcc8f00-c54a-11eb-9e17-f5555e248a8c.png)

**Comment by russell** [comment] 2021-06-05 06:41
I'm also effected by this, i tried but was unable to debug, form what i can tell, like @willwu5047 If i call `kubernetes-refresh` there then check the contents of `kubernetes-state` it's got very limited state unless i manually run one of the `*-refresh-now` functions.

**Comment by egh** [comment] 2021-06-10 17:37
I also have this issue. It seems to be reproducible out of the box (that is, with no `kubernetes-*` variables changed.

emacs: `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2021-06-06` (installed via snap on ubuntu

The problem seems to have been introduced with e7258b4280905cf4cb4348ec385b233dec07893e which does not seem to trigger the correct set of `kubernetes-*-refresh-now` methods.

I can fix by using this workaround:
```
(use-package kubernetes
  :ensure t
  :config (defun kubernetes-overview--poll (&optional verbose)
  (kubernetes-configmaps-refresh verbose)
  (kubernetes-contexts-refresh verbose)
  (kubernetes-ingress-refresh verbose)
  (kubernetes-jobs-refresh verbose)
  (kubernetes-deployments-refresh verbose)
  (kubernetes-statefulsets-refresh verbose)
  (kubernetes-nodes-refresh verbose)
  (kubernetes-namespaces-refresh verbose)
  (kubernetes-pods-refresh verbose)
  (kubernetes-secrets-refresh verbose)
  (kubernetes-services-refresh verbose)))
```

but that does hit `kubectl` pretty hard.

**Comment by egh** [comment] 2021-06-10 20:59
The problem seems to be that the "aggregate" `overview` section is not compatible with this more restricted refresh.
Here is another solution:
```
  (defun kubernetes-overview--poll (&optional verbose)
  (let ((sections (kubernetes-state-overview-sections (kubernetes-state))))
    (when (member 'overview sections)
      (kubernetes-configmaps-refresh verbose)
      (kubernetes-contexts-refresh verbose)
      (kubernetes-ingress-refresh verbose)
      (kubernetes-jobs-refresh verbose)
      (kubernetes-deployments-refresh verbose)
      (kubernetes-statefulsets-refresh verbose)
      (kubernetes-nodes-refresh verbose)
      (kubernetes-namespaces-refresh verbose)
      (kubernetes-pods-refresh verbose)
      (kubernetes-secrets-refresh verbose)
      (kubernetes-services-refresh verbose)))
    (when (member 'configmaps sections)
      (kubernetes-configmaps-refresh verbose))
    (when (member 'context sections)
      (kubernetes-contexts-refresh verbose))
    (when (member 'ingress sections)
      (kubernetes-ingress-refresh verbose))
    (when (member 'jobs sections)
      (kubernetes-jobs-refresh verbose))
    (when (member 'deployments sections)
      (kubernetes-deployments-refresh verbose))
    (when (member 'statefulsets sections)
      (kubernetes-statefulsets-refresh verbose))
    (when (member 'nodes sections)
      (kubernetes-nodes-refresh verbose))
    (when (member 'namespaces sections)
      (kubernetes-namespaces-refresh verbose))
    (when (member 'pods sections)
      (kubernetes-pods-refresh verbose))
    (when (member 'secrets sections)
      (kubernetes-secrets-refresh verbose))
    (when (member 'services sections)
      (kubernetes-services-refresh verbose)))
```

**Comment by noorul** [comment] 2021-06-11 03:50
@egh  So basically we have to go back to the non-performant version

**Comment by noorul** [comment] 2021-06-11 04:09
@egh Looked at the code a little bit deeper and I think we only need to refresh pods, config maps, and secrets. See #157

**Comment by egh** [comment] 2021-06-11 04:39
> Looked at the code a little bit deeper and I think we only need to refresh pods, config maps, and secrets. See #157

I think that's correct, that seems to work for me.

**Closed** 2021-06-11 08:16 UTC

**Comment by egh** [comment] 2021-06-11 14:30
Thank you for fixing this @noorul !
